export default {
	'align-content': {
		'baseline': '.align-content-baseline',
		'center': '.align-content-center',
		'end': '.align-content-end',
		'first baseline': '.align-content-first-baseline',
		'flex-end': '.align-content-flex-end',
		'flex-start': '.align-content-flex-start',
		'last baseline': '.align-content-last-baseline',
		'normal': '.align-content-normal',
		'safe center': '.align-content-safe-center',
		'safe end': '.align-content-safe-end',
		'safe flex-end': '.align-content-safe-flex-end',
		'safe flex-start': '.align-content-safe-flex-start',
		'safe start': '.align-content-safe-start',
		'space-around': '.align-content-space-around',
		'space-between': '.align-content-space-between',
		'space-evenly': '.align-content-space-evenly',
		'start': '.align-content-start',
		'stretch': '.align-content-stretch',
		'unsafe center': '.align-content-unsafe-center',
		'unsafe end': '.align-content-unsafe-end',
		'unsafe flex-end': '.align-content-unsafe-flex-end',
		'unsafe flex-start': '.align-content-unsafe-flex-start',
		'unsafe start': '.align-content-unsafe-start'
	},
	'align-items': {
		'baseline': '.align-items-baseline',
		'center': '.align-items-center',
		'end': '.align-items-end',
		'first baseline': '.align-items-first-baseline',
		'first center': '.align-items-first-center',
		'first end': '.align-items-first-end',
		'first flex-end': '.align-items-first-flex-end',
		'first flex-start': '.align-items-first-flex-start',
		'first self-end': '.align-items-first-self-end',
		'first self-start': '.align-items-first-self-start',
		'first start': '.align-items-first-start',
		'flex-end': '.align-items-flex-end',
		'flex-start': '.align-items-flex-start',
		'last baseline': '.align-items-last-baseline',
		'last center': '.align-items-last-center',
		'last end': '.align-items-last-end',
		'last flex-end': '.align-items-last-flex-end',
		'last flex-start': '.align-items-last-flex-start',
		'last self-end': '.align-items-last-self-end',
		'last self-start': '.align-items-last-self-start',
		'last start': '.align-items-last-start',
		'normal': '.align-items-normal',
		'self-end': '.align-items-self-end',
		'self-start': '.align-items-self-start',
		'start': '.align-items-start',
		'stretch': '.align-items-stretch'
	},
	'align-self': {
		'auto': '.align-self-auto',
		'baseline': '.align-self-baseline',
		'center': '.align-self-center',
		'end': '.align-self-end',
		'first baseline': '.align-self-first-baseline',
		'flex-end': '.align-self-flex-end',
		'flex-start': '.align-self-flex-start',
		'last baseline': '.align-self-last-baseline',
		'normal': '.align-self-normal',
		'safe center': '.align-self-safe-center',
		'safe end': '.align-self-safe-end',
		'safe flex-end': '.align-self-safe-flex-end',
		'safe flex-start': '.align-self-safe-flex-start',
		'safe self-end': '.align-self-safe-self-end',
		'safe self-start': '.align-self-safe-self-start',
		'safe start': '.align-self-safe-start',
		'self-end': '.align-self-self-end',
		'self-start': '.align-self-self-start',
		'start': '.align-self-start',
		'stretch': '.align-self-stretch',
		'unsafe center': '.align-self-unsafe-center',
		'unsafe end': '.align-self-unsafe-end',
		'unsafe flex-end': '.align-self-unsafe-flex-end',
		'unsafe flex-start': '.align-self-unsafe-flex-start',
		'unsafe self-end': '.align-self-unsafe-self-end',
		'unsafe self-start': '.align-self-unsafe-self-start',
		'unsafe start': '.align-self-unsafe-start'
	}
}